name: Test & Release CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Current Branch
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Bootstrap Dependencies
        run: npm run bootstrap

      - name: Run Testing Suite
        run: npm run lib:test

      - name: NPM Identity
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Release Package
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          if [ ${{ env.CURRENT_BRANCH }} = dev ]; then
            npm run lib:bump:next
            npm run lib:publish:next
          fi
