name: Test & Release CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Current Branch
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Bootstrap Dependencies
        run: npm run bootstrap

      - name: Run Testing Suite
        run: npm run lib:test

      - name: Release Package
        run: |
          if [ ${{ env.CURRENT_BRANCH }} = dev ]; then
            npm run lib:bump:next
          fi
