name: Testing CI

on:
  push:
    branches:
      - main
      - feat/v3
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: npm run bootstrap
      - run: npx run lib:test
