name: Testing CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - run: pnpm run lib:test
